#server.port: 9966
spring.profiles: default

management.security.enabled: false

spring.jpa.hibernate.ddl-auto: validate

spring.datasource:
  url: "jdbc:h2:mem:testdb"
  driverClassName: org.h2.Driver
  username: sa
  password: ""
  #data: "classpath*:data.sql"
spring.jpa:
  database-platform: org.hibernate.dialect.H2Dialect

spring.h2.console.enabled: true

#flyway.enabled: true
flyway.locations: classpath:db/migration/
